mqtt_bridge_node:
  ros__parameters:
    mqtt:
      client:
        protocol: 4      # MQTTv311
      connection:
        host: "localhost"
        port: 1883
        keepalive: 60
      private_path: "device/001"
    serializer: json:dumps
    deserializer: json:loads
    n_bridges: 2
    bridge:
      bridge1: ["mqtt_bridge.bridge:RosToMqttBridge","std_msgs.msg:String","/chatter","chatter"]
      bridge2: ["mqtt_bridge.bridge:RosToMqttBridge","geometry_msgs.msg:Twist","/cmd_vel","cmd_vel"]
 